### ISSUE TITLE
Error Message and only one click then nothing else

### ISSUE THREAD

**Issue by ChrizzHose** [Hegemege/molek-syntez-solitaire-bot#1]
https://imgur.com/a/ynYPTA8

whats the problem here? 
im new into coding would be nice if u could help me out ^^

**Comment by Hegemege** [comment]
Please check the instructions again - looks like the game window was not positioned correctly and the bot couldn't take a screenshot of the game window.

The script works if your game is fullscreen in 1080p or 1440p, or if you have the game windowed (and centered) in 1080p on larger resolution desktop. If you have a resolution lower than 1080p, then it might not work straight out of the box unfortunately.

The script performs one click at the beginning in order to focus the game window, and then tries to take a screenshot. It's a bit finicky but I hope you can get it working!
